version: '2'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  db:
    image: mdillon/postgis
    environment:
      POSTGRES_DB: 'nxtl_shc_api_db'
      POSTGRES_PASSWORD: 'nxtl'
      POSTGRES_USER: 'nxtl'
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data